ALTER TABLE USERS
ADD IS_HOST NUMBER(1);

CREATE TABLE DEPOSITS (
    USER_ID NUMBER,
    TRANSACTION_ID VARCHAR2(50) UNIQUE,
    BANK_ACC_NO VARCHAR2(35),
    
    CONSTRAINTS DEPOSITS_USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
    CONSTRAINTS DEPOSITS_PAYMENTS_FK FOREIGN KEY(TRANSACTION_ID) REFERENCES PAYMENTS(TRANSACTION_ID)
);

CREATE OR REPLACE TRIGGER UPDATE_DEPOSITS
FOR INSERT
ON RENTS
COMPOUND TRIGGER
    UID NUMBER;
    USER_BANK_ACC_NO VARCHAR2(35);

    BEFORE EACH ROW IS
    BEGIN
        SELECT BANK_ACC_NO INTO USER_BANK_ACC_NO
        FROM USERS WHERE USER_ID = :NEW.USER_ID;
        
        IF USER_BANK_ACC_NO IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'Transaction cant be completed. User doesnt have bank account no');
        END IF;
    END BEFORE EACH ROW;

    AFTER EACH ROW IS
    BEGIN
        SELECT USER_ID INTO UID
        FROM HOUSES WHERE HOUSE_ID = :NEW.HOUSE_ID;
        
        INSERT INTO DEPOSITS
        VALUES(UID, :NEW.TRANSACTION_ID, USER_BANK_ACC_NO);
    END AFTER EACH ROW;
END;