CREATE OR REPLACE FUNCTION GET_MIN_PRICE(HID IN NUMBER)
RETURN NUMBER IS 
    MIN_PRICE NUMBER;
BEGIN
    SELECT MIN(NVL(PRICE, 0)) INTO MIN_PRICE
    FROM ROOMS
    WHERE HOUSE_ID = HID;
    
    RETURN MIN_PRICE;
END;
    
CREATE OR REPLACE FUNCTION GET_MAX_PRICE(HID IN NUMBER)
RETURN NUMBER IS 
    MAX_PRICE NUMBER;
BEGIN
    SELECT MAX(NVL(PRICE, 0)) INTO MAX_PRICE
    FROM ROOMS
    WHERE HOUSE_ID = HID;
    
    RETURN MAX_PRICE;
END;

CREATE OR REPLACE FUNCTION INSERT_HOUSE_RETURN_HOUSE_ID(USRID IN NUMBER, AID IN NUMBER, HNAME IN VARCHAR2, 
HNO IN VARCHAR2, DESCR IN VARCHAR2)
RETURN NUMBER IS
		HID NUMBER;
BEGIN
    INSERT INTO HOUSES(USER_ID,ADDRESS_ID,HOUSE_NAME,HOUSE_NO,DESCRIPTION) 
    VALUES(USRID, AID, HNAME, HNO, DESCR) RETURNING HOUSE_ID INTO HID;
		
	RETURN HID;
END;

CREATE OR REPLACE FUNCTION INSERT_ADDRESS_RETURN_ADDRESS_ID(STR IN VARCHAR2, PC IN VARCHAR2, CID IN NUMBER)
RETURN NUMBER IS
		AID NUMBER;
BEGIN
    INSERT INTO ADDRESSES(STREET, POST_CODE, CITY_ID) 
    VALUES(STR, PC, CID) RETURNING ADDRESS_ID INTO AID;
		
	RETURN AID;
END;

CREATE OR REPLACE FUNCTION IS_ROOM_AVAILABLE(HID IN NUMBER, RN IN NUMBER, CID IN VARCHAR2, COD IN VARCHAR2, G IN NUMBER)
RETURN CHAR IS
	CNT NUMBER;
	CAPACITY NUMBER;
BEGIN
	SELECT MAX_CAPACITY INTO CAPACITY
	FROM ROOMS
	WHERE HOUSE_ID = HID
	AND ROOM_NO = RN;
	
	IF G <= CAPACITY THEN
		SELECT COUNT(ROOM_NO) INTO CNT
		FROM RENTS
		WHERE HOUSE_ID = HID
		AND ROOM_NO = RN
		AND ((TO_DATE(CID, 'DD-MON-YYYY') BETWEEN CHECKIN AND CHECKOUT)
		OR (TO_DATE(COD, 'DD-MON-YYYY') BETWEEN CHECKIN AND CHECKOUT)
		OR (CHECKIN BETWEEN TO_DATE(CID, 'DD-MON-YYYY') AND TO_DATE(COD, 'DD-MON-YYYY')));
	
		IF CNT = 0 THEN
			RETURN 'Y';
		ELSE
			RETURN 'N';
		END IF;
	END IF;
	RETURN 'N';
END;

CREATE OR REPLACE TRIGGER UPDATE_DEPOSITS
FOR INSERT
ON RENTS
COMPOUND TRIGGER
    UID NUMBER;
    USER_BANK_ACC_NO VARCHAR2(35);

    BEFORE EACH ROW IS
    BEGIN
        SELECT BANK_ACC_NO INTO USER_BANK_ACC_NO
        FROM USERS WHERE USER_ID = :NEW.USER_ID;
        
        IF USER_BANK_ACC_NO IS NULL THEN
            RAISE_APPLICATION_ERROR(-20001, 'Transaction cant be completed. Owner doesnt have bank account no');
        END IF;
    END BEFORE EACH ROW;

    AFTER EACH ROW IS
    BEGIN
        SELECT USER_ID INTO UID
        FROM HOUSES WHERE HOUSE_ID = :NEW.HOUSE_ID;
        
        INSERT INTO DEPOSITS
        VALUES(UID, :NEW.TRANSACTION_ID, USER_BANK_ACC_NO);
    END AFTER EACH ROW;
END;

CREATE OR REPLACE TRIGGER MAKE_HOST
AFTER INSERT
ON HOUSES
FOR EACH ROW
DECLARE
    ISHOST NUMBER(1);
BEGIN
    DBMS_OUTPUT.PUT_LINE('Make host triggered ' || :NEW.USER_ID);
    UPDATE USERS
    SET IS_HOST = 1
    WHERE USER_ID = :NEW.USER_ID;
    DBMS_OUTPUT.PUT_LINE('Host ADDED');
END;

CREATE OR REPLACE TRIGGER REMOVE_HOST
AFTER DELETE
ON HOUSES
FOR EACH ROW
DECLARE
	NO_OF_HOUSES NUMBER;
	HID NUMBER := 0;
	PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
	DBMS_OUTPUT.PUT_LINE('Remove host triggered');
	SELECT COUNT(HOUSE_ID) INTO NO_OF_HOUSES
	FROM HOUSES
	WHERE USER_ID = :OLD.USER_ID;
	
	IF NO_OF_HOUSES = 1 THEN
		SELECT HOUSE_ID INTO HID
		FROM HOUSES
		WHERE USER_ID = :OLD.USER_ID;
	END IF;
	
	IF NO_OF_HOUSES = 1 AND HID = :OLD.HOUSE_ID THEN
		UPDATE USERS
		SET IS_HOST = 0
		WHERE USER_ID = :OLD.USER_ID;
		DBMS_OUTPUT.PUT_LINE('Host removed');
	END IF;
	COMMIT;
END;


-- New Added pl sql

-- Deleting values from DEPOSITS
CREATE OR REPLACE TRIGGER DEL_DEPOSITS
BEFORE DELETE
ON DEPOSITS
FOR EACH ROW
DECLARE
BEGIN
	DELETE FROM PAYMENTS WHERE TRANSACTION_ID=:OLD.TRANSACTION_ID;
	DBMS_OUTPUT.PUT_LINE('DEPOSITS DELETED');
END;

-- Deleting values from ROOMS
CREATE OR REPLACE TRIGGER DEL_ROOMS
BEFORE DELETE
ON ROOMS
FOR EACH ROW
DECLARE
BEGIN
	DELETE FROM ROOM_PHOTOS_PATH WHERE ROOM_NO=:OLD.ROOM_NO AND HOUSE_ID=:OLD.HOUSE_ID;
	DELETE FROM RENTS WHERE ROOM_NO=:OLD.ROOM_NO;
	DBMS_OUTPUT.PUT_LINE('ROOM DELETED');
END;

-- Deleting values from HOUSES
CREATE OR REPLACE TRIGGER DEL_HOUSES
BEFORE DELETE
ON HOUSES
FOR EACH ROW
DECLARE
BEGIN
	DELETE FROM HOUSE_PHOTOS_PATH WHERE HOUSE_ID=:OLD.HOUSE_ID;
	DELETE FROM ROOMS WHERE HOUSE_ID=:OLD.HOUSE_ID;
	DELETE FROM RENTS WHERE HOUSE_ID=:OLD.HOUSE_ID;
	DBMS_OUTPUT.PUT_LINE('HOUSE DELETED');
END;

-- Deleting values from USERS
CREATE OR REPLACE TRIGGER DEL_USERS
BEFORE DELETE
ON USERS
FOR EACH ROW
DECLARE
BEGIN
	DELETE FROM HOUSES WHERE USER_ID=:OLD.USER_ID;
	DELETE FROM RENTS WHERE USER_ID=:OLD.USER_ID;
	DELETE FROM DEPOSITS WHERE USER_ID=:OLD.USER_ID;
	DBMS_OUTPUT.PUT_LINE('USER DELETED');
END;