CREATE TYPE BANK_ACC_NO_VA AS VARRAY(3) OF VARCHAR2(35);
CREATE TYPE CREDIT_CARD_NO_VA AS VARRAY(3) OF VARCHAR2(16);

CREATE TABLE USERS (
	USER_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) CONSTRAINT PERSON_PK PRIMARY KEY, 
	USERNAME VARCHAR2(50) NOT NULL UNIQUE ,
	FIRST_NAME VARCHAR2(25),
	LAST_NAME VARCHAR2(25),
	EMAIL VARCHAR2(50) NOT NULL UNIQUE,
	PHONE_NO VARCHAR2(20),
	PASSWORD VARCHAR2(255) NOT NULL,
	BANK_ACC_NO BANK_ACC_NO_VA,
	CREDIT_CARD_NO CREDIT_CARD_NO_VA,
	POINTS NUMBER(6,0)
);

CREATE TABLE HOUSES
(
	HOUSE_ID NUMBER GENERATED ALWAYS AS IDENTITY(START WITH 1 INCREMENT BY 1) CONSTRAINT HOUSE_PK PRIMARY KEY,
	USER_ID NUMBER NOT NULL UNIQUE,
	ADDRESS_ID NUMBER NOT NULL UNIQUE,
	HOUSE_NAME VARCHAR2(20),
	HOUSE_NO NUMBER NOT NULL,
	DESCRIPTION VARCHAR2(255),
	PHOTOS_PATH VARCHAR2(100),
	
	CONSTRAINT HOUSE_OWNER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
	CONSTRAINT HOUSE_ADDRESS_FK FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESSES(ADDRESS_ID)
);

CREATE TABLE ADDRESSES 
(
	ADDRESS_ID NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1) CONSTRAINT ADDRESS_PK PRIMARY KEY,
	STREET VARCHAR2(50) NOT NULL,
	POST_CODE VARCHAR2(20) NOT NULL,
	CITY_NAME VARCHAR2(20) NOT NULL,
	STATE VARCHAR2(20) NOT NULL,
	COUNTRY_NAME VARCHAR2(60) NOT NULL
);

CREATE TABLE PAYMENTS
(
	TRANSACTION_ID VARCHAR2(10) CONSTRAINT PAYMENT_PK PRIMARY KEY,
	TRANSACTION_DATE DATE DEFAULT SYSDATE NOT NULL,
	AMOUNT NUMBER NOT NULL,
	PAYMENT_METHOD VARCHAR2(10)
);

CREATE TABLE RENTS
(
	USER_ID NUMBER NOT NULL,
	HOUSE_ID NUMBER NOT NULL,
	ROOM_NO NUMBER NOT NULL,
	TRANSACTION_ID VARCHAR2(10),
	REVIEW NUMBER,
	REVIEW_COMMENT VARCHAR2(255),
	CHECKIN DATE NOT NULL,
	CHECKOUT DATE NOT NULL,
	CONSTRAINT RENT_USER_FK FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID),
	CONSTRAINT RENT_PAYMENT_FK FOREIGN KEY(TRANSACTION_ID) REFERENCES PAYMENTS(TRANSACTION_ID),
	CONSTRAINT RENT_ROOM_FK FOREIGN KEY(HOUSE_ID, ROOM_NO) REFERENCES ROOMS(HOUSE_ID, ROOM_NO)
);

CREATE TABLE ROOMS 
(
	HOUSE_ID NUMBER NOT NULL,
	ROOM_NO NUMBER NOT NULL,
	PHOTOS_PATH VARCHAR2(100),
	MAX_CAPACITY NUMBER,
	DESCRIPTION VARCHAR2(255),
	PRICE NUMBER NOT NULL,
	OFFER_PCT NUMBER,
	CONSTRAINT ROOM_HOUSE_FK FOREIGN KEY(HOUSE_ID) REFERENCES HOUSES(HOUSE_ID),
	CONSTRAINT ROOM_PK PRIMARY KEY(HOUSE_ID, ROOM_NO)
);
